### ISSUE TITLE
OnInterstitialLoaded does not work on iOS

### ISSUE THREAD

**Issue by ablohme86** [marcojak/MTAdmob#118] opened 2022-11-13 18:33 UTC
**Describe the bug**
OnInterstitialLoaded, OnRewardedVideoAdLoaded and OnRewardedVideoAdFailedToLoad never fires on iOS

**To Reproduce**
Add CrossMTAdmob.Current.OnInterstitialLoaded += Current_OnInterstitialLoaded; to your project

**Expected behavior**
It should load an ad or throw something to OnRewardedVideoAdFailedToLoad

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari

**Smartphone (please complete the following information):**
 - Device: iPhone12 Pro, iPhone 13 Pro, Simulators
 - OS: iOS 16

**Additional context**
Banner works fine

**Comment by prok155** [comment] 2022-11-15 18:19
Duplicate #111

@marcojak are there any plans to fix it soon? We can't use 1.8.0 version because of this bug :(

**Comment by ablohme86** [comment] 2022-11-15 20:33
> Duplicate #111
> 
> @marcojak are there any plans to fix it soon? We can't use 1.8.0 version because of this bug :(

So I am not the only one?

**Comment by marcojak** [comment] 2022-11-15 20:44
I'm currently working on version 1.9 that fixes few issues and adds new features.
The version for Android is complete and I now have to work on the one for iOS.
I hope I can release it very soon.

**Comment by ablohme86** [comment] 2022-11-15 20:47
What version can I use that doesnt break android using target 12?

**Comment by marcojak** [comment] 2022-11-15 20:49
Even the current version works fine with android 12. There is a package you
need to update (you can find which one in one of the issues opened for this
plugin).

I'm testing the new version on Android 11, 12 and 13!

**Comment by ablohme86** [comment] 2022-11-15 20:50
Yes, but to fix this tempoarily on iOS can I use 1.6.9 on iOS and 1.8.0 on Android the same time?

**Comment by marcojak** [comment] 2022-11-15 20:53
You could try, right now I don't remember the differences between the two
versions. It might work but it's very possible that it will not. You could
use the previous version on both platforms.

**Comment by ablohme86** [comment] 2022-11-15 21:01
I tried to downgrade but it now throws this: 
<img width="557" alt="Screenshot 2022-11-15 at 22 00 15" src="https://user-images.githubusercontent.com/17109732/202024445-30aad01b-ffb0-44f6-ad18-f3f6a2d40e30.png">

Any idea what I do wrong? I only use OnLoadedInterstital and Show interstitial when it fires

**Comment by ablohme86** [comment] 2022-11-15 21:49
> I tried to downgrade but it now throws this: <img alt="Screenshot 2022-11-15 at 22 00 15" width="557" src="https://user-images.githubusercontent.com/17109732/202024445-30aad01b-ffb0-44f6-ad18-f3f6a2d40e30.png">
> 
> Any idea what I do wrong? I only use OnLoadedInterstital and Show interstitial when it fires

Nevermind, I forgot to downgrade ios.Ads to 7.66

**Comment by marcojak** [comment] 2022-12-03 12:00
The new version is out and that should fix the issue.
Closing it for now but feel free to open a new one if the issue is still present

**Closed by marcojak** 2022-12-03 12:00 UTC
