### ISSUE TITLE
Doesn't work on Xamarin Forms in iOS

### ISSUE THREAD

**Issue by freezersharp** [marcojak/MTAdmob#56] opened 2021-04-26 17:37 UTC
**Describe the bug**
It doesn't work on iOS, it doesn't compile in Release mode. In debug mode, the ads don't show.

**To Reproduce**
1. Add the nuget package (and another 2 nugets from Google, followin some tutorials without success).
2. Change to Release mode.
3. Archive the iOS project.
4. Get a lot of errors!!

**Expected behavior**
To archive successfully to generate the ipa file.

**Screenshots**

**Desktop (please complete the following information):**
Lastest VS (in Windows) and macOS version, all the lastest version nugets.

**Smartphone (please complete the following information):**
 - Any device.

**Comment by marcojak** [comment] 2021-04-26 18:59
Try to clean you project and delete all your bin & obj folders.
I personally have this plugin on several apps on iOS and it works perfectly fine.

**Comment by freezersharp** [comment] 2021-04-26 20:02
It doesn't work, even I deleted the bin and obj folders (in project folder and the temp files in Mac).
An error occurred: 'Object reference not set to an instance of an object.'. Callstack: '  at IDDAM_SV.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00024] in C:\Proyectos\Iguanas\IDDAM\IDDAM_SV.iOS\AppDelegate.cs:30 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65 
  at IDDAM_SV.iOS.Application.Main (System.String[] args) [0x00001] in C:\Proyectos\Iguanas\IDDAM\IDDAM_SV.iOS\Main.cs:17 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:395 '

The AppDelegate's line is this:
     MobileAds.SharedInstance.Start(CompletionHandler);


If I debug it and I create a breakpoint in  this line, MobileAds.SharedInstance is null.

I tried this:

 if (MobileAds.SharedInstance != null)
            {
                MobileAds.SharedInstance.Start(CompletionHandler);
            }

without success, it doesn't make sense but I tried. I follow all the instructions and different tutorials (in the last one, I read about the another google nugets but they are not necessary in the lastest Admob nuget version.

What am I missing?

**Comment by marcojak** [comment] 2021-04-26 20:35
What's your setting of "Linker Behavior" on iOS?

**Comment by marcojak** [comment] 2021-04-26 20:37
Another thing to notice. In you Info.plist you should have:
	<key>GADApplicationIdentifier</key>
	<string>YOUR KEY</string>
	<key>GADIsAdManagerApp</key>
	<true/>

**Comment by marciosouzajunior** [comment] 2021-04-26 20:51
Same here. I'm in debug mode, link behavior "don't link" and have filled Info.plist.

**Comment by marcojak** [comment] 2021-04-26 20:54
Check that you have installed this plugin in iOS: Xamarin.Google.iOS.MobileAds

**Comment by marciosouzajunior** [comment] 2021-04-26 20:57
It's not installed. My case seems related to #37 because I'm also building with hotreload. I will try to build another way.

**Comment by marcojak** [comment] 2021-04-26 21:21
I've added the info on the ReadMe in case it will happen for someone else.

I'm closing this issue but if the problem is different, feel free to open it again!

**Closed by marcojak** 2021-04-26 21:21 UTC
