### ISSUE TITLE
Crash In Release Mode (Android)

### ISSUE THREAD

**Issue by mistrypragnesh40** [marcojak/MTAdmob#98] opened 2022-02-27 15:06 UTC
**Describe the bug**
After installing MarcTron.Admob 1.6.9,  Application crashing on startup.

**To Reproduce**
1. Install the Admob 1.6.9 Package.
2. Try to run app in release mode with  following configuraiton
            1. Dex Compiler d8
            2. Code Shrinker r8
3. Run the application in release mode.
4. App Will Crash on Start Up.

Further info:
I am using target framework for compiling is : Android 12.0 (S)

**Expected behavior**
App Should not crash.

**Comment by Roccosco** [comment] 2022-03-15 10:23
I also have this problem.

**Comment by marcojak** [comment] 2022-03-29 20:43
The problem is caused by R8 that removes some needed classes.

To solve the error, in the Android project add the file ProGuard.cfg and set its build action as ProguardConfiguration.
Inside the empty file add these two lines:

-keep class com.google.android.gms.ads.MobileAdsInitProvider
-keep class androidx.work.impl.WorkManagerInitializer

I've tested it with the SampleMTAdmob project and it works fine.

I'm closing the issue now but if you still have problems, feel free to reopen it.

**Closed by marcojak** 2022-03-29 20:43 UTC

**Comment by gsgou** [comment] 2022-06-09 15:04
I was still getting crashes on Android devices. Following proguard config fixed my issues:
-keep public class com.google.android.gms.ads.** { public *; }
-keep public class com.google.ads.** { public *; }
-keep class androidx.work.impl.WorkManagerInitializer
